################################################################################
#
# ti-framework-components
#
################################################################################
TI_FRAMEWORK_COMPONENTS_VERSION:=2.25.02.06
TI_FRAMEWORK_COMPONENTS_FILE_VERSION:=2_25_02_06
TI_FRAMEWORK_COMPONENTS_SOURCE:=framework_components_$(TI_FRAMEWORK_COMPONENTS_FILE_VERSION),lite.tar.gz
TI_FRAMEWORK_COMPONENTS_SITE:=http://software-dl.ti.com/dsps/dsps_public_sw/sdo_sb/targetcontent/fc/$(TI_FRAMEWORK_COMPONENTS_FILE_VERSION)/exports
TI_FRAMEWORK_COMPONENTS_DIR:=$(BUILD_DIR)/ti-framework-components-$(TI_FRAMEWORK_COMPONENTS_VERSION)

TI_FRAMEWORK_COMPONENTS_INSTALL_TARGET = NO
TI_FRAMEWORK_COMPONENTS_INSTALL_STAGING = YES

TI_FRAMEWORK_COMPONENTS_INSTALL_DIR:=$(STAGING_DIR)/ti/framework-components-$(TI_FRAMEWORK_COMPONENTS_VERSION)


$(DL_DIR)/$(TI_FRAMEWORK_COMPONENTS_SOURCE):
	$(call DOWNLOAD,$(TI_FRAMEWORK_COMPONENTS_SITE),$(TI_FRAMEWORK_COMPONENTS_SOURCE))

define TI_FRAMEWORK_COMPONENTS_INSTALL_STAGING_CMDS
	mkdir -p $(TI_FRAMEWORK_COMPONENTS_INSTALL_DIR)
	cp -pPrf $(TI_FRAMEWORK_COMPONENTS_DIR)/* $(TI_FRAMEWORK_COMPONENTS_INSTALL_DIR)
	chmod -R +w $(TI_FRAMEWORK_COMPONENTS_INSTALL_DIR)
endef

define TI_FRAMEWORK_COMPONENTS_UNINSTALL_STAGING_CMDS
	rm -rf $(TI_FRAMEWORK_COMPONENTS_INSTALL_DIR)
endef


ti-framework-components-source: $(DL_DIR)/$(TI_FRAMEWORK_COMPONENTS_SOURCE)

$(eval $(call GENTARGETS,package/ti,ti-framework-components))