################################################################################
#
# ti-local-power-manager
#
################################################################################
TI_LOCAL_POWER_MANAGER_VERSION:=1.24.02.09
TI_LOCAL_POWER_MANAGER_FILE_VERSION:=1_24_02_09
TI_LOCAL_POWER_MANAGER_SOURCE = local_power_manager_linux_$(TI_LOCAL_POWER_MANAGER_FILE_VERSION).tar.gz
TI_LOCAL_POWER_MANAGER_SITE=http://software-dl.ti.com/dsps/dsps_public_sw/sdo_sb/targetcontent/lpm/$(TI_LOCAL_POWER_MANAGER_FILE_VERSION)/exports
TI_LOCAL_POWER_MANAGER_DIR:=$(BUILD_DIR)/ti-local-power-manager-$(TI_LOCAL_POWER_MANAGER_VERSION)

TI_LOCAL_POWER_MANAGER_INSTALL_STAGING = YES

TI_LOCAL_POWER_MANAGER_DEPENDENCIES = ti-xdctools ti-dsplink linux

TI_LOCAL_POWER_MANAGER_INSTALL_STAGING_DIR=$(STAGING_DIR)/ti/local-power-manager-$(TI_LOCAL_POWER_MANAGER_VERSION)

TI_LOCAL_POWER_MANAGER_PLATFORM=UNDEFINED
TI_LOCAL_POWER_MANAGER_XDC_PLATFORM=UNDEFINED
TI_LOCAL_POWER_MANAGER_XDC_PLATFORM_DIR=UNDEFINED
ifeq ($(BR2_PACKAGE_TI_PLATFORM_omap3),y)
	TI_LOCAL_POWER_MANAGER_PLATFORM=omap3530
	TI_LOCAL_POWER_MANAGER_XDC_PLATFORM=ti.platforms.evm3530
	TI_LOCAL_POWER_MANAGER_XDC_PLATFORM_DIR=ti_platforms_evm3530
endif
ifeq ($(BR2_PACKAGE_TI_PLATFORM_dm6446),y)
	TI_LOCAL_POWER_MANAGER_PLATFORM=dm6446
	TI_LOCAL_POWER_MANAGER_XDC_PLATFORM=ti.platforms.evmDM6446
	TI_LOCAL_POWER_MANAGER_XDC_PLATFORM_DIR=ti_platforms_evmDM6446
endif

define TI_LOCAL_POWER_MANAGER_CONFIG
	/* Generated by ti-local-power-manager.inc OE recipe */
	var Build = xdc.useModule('xdc.bld.BuildEnvironment');
	var GCArmv5T = xdc.useModule('gnu.targets.arm.GCArmv5T');
	GCArmv5T.LONGNAME = "$(TARGET_CC)";
	GCArmv5T.rootDir = "$(TARGET_CROSS)";
	GCArmv5T.ccOpts.prefix += " -Wall -fno-strict-aliasing ";
	GCArmv5T.lnkOpts.suffix = GCArmv5T.lnkOpts.suffix.replace("-lstdc++", "");
	GCArmv5T.lnkOpts.suffix += " -lpthread ";
	GCArmv5T.platform = null;
	GCArmv5T.platforms = [ "$(TI_LOCAL_POWER_MANAGER_XDC_PLATFORM)" ];
	/* remove unused profiles */
	delete GCArmv5T.profiles[\"coverage\"];
	delete GCArmv5T.profiles[\"profile\"];
	Build.targets.\$add(GCArmv5T);
endef
export TI_LOCAL_POWER_MANAGER_CONFIG

define TI_LOCAL_POWER_MANAGER_CONFIGURE_CMDS
	@echo  "$$TI_LOCAL_POWER_MANAGER_CONFIG" > $(@D)/config.bld
	(cd $(TI_LOCAL_POWER_MANAGER_DIR); XDCPATH=$(TI_XDCTOOLS_INSTALL_DIR) $(TI_XDCTOOLS_INSTALL_DIR)/xdc .make -PR .)
	(cd $(TI_LOCAL_POWER_MANAGER_DIR); XDCPATH=$(TI_XDCTOOLS_INSTALL_DIR) $(TI_XDCTOOLS_INSTALL_DIR)/xdc clean -PR .)
endef

define TI_LOCAL_POWER_MANAGER_BUILD_CMDS
	# Build the gpp user space library
 	$(MAKE1) -C $(@D)/packages/ti/bios/power/modules/$(TI_LOCAL_POWER_MANAGER_PLATFORM)/lpm \
		DSPLINK_REPO=$(TI_DSPLINK_INSTALL_STAGING_DIR) \
  	LINUXKERNEL_INSTALL_DIR="$(BUILD_DIR)/linux-$(LINUX_VERSION)" \
		MVTOOL_PREFIX="$(TARGET_CROSS)" \
  		clean default
	#TODO: Build the user space library
	#TODO: Build the utilities (lpmON/OFF)
	# (cd $(@D); XDCPATH=$(TI_XDCTOOLS_INSTALL_DIR) $(TI_XDCTOOLS_INSTALL_DIR)/xdc -PR .)
endef

define TI_LOCAL_POWER_MANAGER_INSTALL_STAGING_CMDS
	# Install/Stage the Source Tree
	$(INSTALL) -d $(TI_LOCAL_POWER_MANAGER_INSTALL_STAGING_DIR)
	cp -a $(TI_LOCAL_POWER_MANAGER_DIR)/* $(TI_LOCAL_POWER_MANAGER_INSTALL_STAGING_DIR)
	chmod -R +w $(TI_LOCAL_POWER_MANAGER_INSTALL_STAGING_DIR)
endef

define TI_LOCAL_POWER_MANAGER_INSTALL_TARGET_CMDS
	# Install the kernel module 
	$(INSTALL) -d $(TARGET_DIR)/lib/modules/$(LINUX_VERSION_PROBED)/kernel/drivers/dsp
	$(INSTALL) -m 0644 $(TI_LOCAL_POWER_MANAGER_DIR)/packages/ti/bios/power/modules/$(TI_LOCAL_POWER_MANAGER_PLATFORM)/lpm/*.ko $(TARGET_DIR)/lib/modules/$(LINUX_VERSION_PROBED)/kernel/drivers/dsp
	#TODO: Install the Utilities
	# install -d $(TARGET_DIR)/usr/lib/ti-lpm-utils
	# install -m 0755 $(TI_LOCAL_POWER_MANAGER_DIR)/packages/ti/bios/power/utils/bin/$(TI_LOCAL_POWER_MANAGER_XDC_PLATFORM_DIR)/linux/release/* $(TARGET_DIR)/usr/lib/ti-lpm-utils
endef

$(eval $(call GENTARGETS,package/ti,ti-local-power-manager))

