################################################################################
#
# ti-gst-plugin
#
################################################################################

TI_GST_PLUGIN_VERSION:=1.01.00
TI_GST_PLUGIN_SOURCE:=gst-ti-plugin-minimal-$(TI_GST_PLUGIN_VERSION).tar.gz
TI_GST_PLUGIN_SITE:=https://gforge.ti.com/gf/download/frsrelease/211/2821/
TI_GST_PLUGIN_DIR:=$(BUILD_DIR)/gst-ti-plugin-minimal-$(TI_GST_PLUGIN_VERSION)

TI_GST_PLUGIN_LIBTOOL_PATCH = NO
TI_GST_PLUGIN_DEPENDENCIES = gstreamer gst-plugins-base

TI_GST_PLUGIN_PLATFORM=UNDEFINED
TI_GST_PLUGIN_XDC_PLATFORM=UNDEFINED
ifeq ($(BR2_PACKAGE_TI_PLATFORM_omap3),y)
	TI_GST_PLUGIN_PLATFORM=omap3530
	TI_GST_PLUGIN_XDC_PLATFORM=ti.platforms.evm3530
	TI_GST_PLUGIN_DEPENDENCIES += ti-codecs-omap3 ti-dmai
	TI_GST_PLUGIN_ENV = \
		PLATFORM=$(TI_GST_PLUGIN_PLATFORM) \
		GST_TI_PLATFORM=$(TI_GST_PLUGIN_PLATFORM) \
		XDC_PLATFORM=$(TI_GST_PLUGIN_XDC_PLATFORM) \
		XDC_TARGET="gnu.targets.arm.GCArmv5T" \
		CROSS_COMPILE=$(TARGET_CROSS) \
		MVTOOL_DIR=$(dir $(TARGET_CROSS)) \
		LINK_XDC_ROOT=$(TI_DSPLINK_INSTALL_STAGING_DIR) \
		CODEC_SERVER=$(TI_CODECS_OMAP3_INSTALL_TARGET_DIR)/cs.x64P \
		XDC_INSTALL_DIR=$(TI_XDCTOOLS_INSTALL_DIR) \
		LINK_INSTALL_DIR=$(TI_DSPLINK_INSTALL_STAGING_DIR)/.. \
		FC_INSTALL_DIR=$(TI_FRAMEWORK_COMPONENTS_INSTALL_DIR) \
		CE_INSTALL_DIR=$(TI_CODEC_ENGINE_DIR) \
		XDAIS_INSTALL_DIR=$(TI_XDAIS_INSTALL_DIR) \
		CMEM_INSTALL_DIR=$(TI_LINUXUTILS_INSTALL_STAGING_DIR) \
		DMAI_INSTALL_DIR=$(TI_DMAI_INSTALL_STAGING_DIR)/dmai \
		LPM_INSTALL_DIR=$(TI_LOCAL_POWER_MANAGER_INSTALL_STAGING_DIR) \
		EDMA3_LLD_INSTALL_DIR=$(TI_EDMA3LLD_INSTALL_DIR) \
		CODEC_INSTALL_DIR=$(TI_CODECS_OMAP3_INSTALL_STAGING_DIR) \
		BIOSUTILS_INSTALL_DIR=$(TI_BIOSUTILS_INSTALL_DIR) \
		CFLAGS="$(TARGET_CFLAGS)" \
		LINUXKERNEL_INSTALL_DIR=$(BUILD_DIR)/linux-$(LINUX26_VERSION)
endif
ifeq ($(BR2_PACKAGE_TI_PLATFORM_dm365),y)
	TI_GST_PLUGIN_PLATFORM=dm365
	TI_GST_PLUGIN_XDC_PLATFORM=ti.platforms.evmDM365
	TI_GST_PLUGIN_DEPENDENCIES += ti-dvsdk-dm365
	TI_GST_PLUGIN_ENV = \
		PLATFORM=$(TI_GST_PLUGIN_PLATFORM) \
		GST_TI_PLATFORM=$(TI_GST_PLUGIN_PLATFORM) \
		XDC_PLATFORM=$(TI_GST_PLUGIN_XDC_PLATFORM) \
		XDC_TARGET="gnu.targets.arm.GCArmv5T" \
		CROSS_COMPILE=$(TARGET_CROSS) \
		MVTOOL_DIR=$(dir $(TARGET_CROSS))/.. \
		LINK_XDC_ROOT=$(TI_DVSDK_DM365_DM365MM_MODULE_INSTALL_DIR) \
		CODEC_SERVER=/usr/lib/ti-codecs\
		XDC_INSTALL_DIR=$(TI_DVSDK_DM365_XDC_INSTALL_DIR) \
		LINK_INSTALL_DIR=$(TI_DVSDK_DM365_DM365MM_MODULE_INSTALL_DIR)\
		FC_INSTALL_DIR=$(TI_DVSDK_DM365_FC_INSTALL_DIR) \
		CE_INSTALL_DIR=$(TI_DVSDK_DM365_CE_INSTALL_DIR) \
		XDAIS_INSTALL_DIR=$(TI_DVSDK_DM365_XDAIS_INSTALL_DIR) \
		CMEM_INSTALL_DIR=$(TI_DVSDK_DM365_LINUXUTILS_INSTALL_DIR) \
		DMAI_INSTALL_DIR=$(TI_DVSDK_DM365_DMAI_INSTALL_DIR) \
		LPM_INSTALL_DIR=$(TI_DVSDK_DM365_DM365MM_MODULE_INSTALL_DIR)   \
		EDMA3_LLD_INSTALL_DIR=$(TI_EDMA3LLD_INSTALL_DIR) \
		CODEC_INSTALL_DIR=$(TI_DVSDK_DM365_CODEC_INSTALL_DIR) \
		BIOSUTILS_INSTALL_DIR=  \
		CFLAGS="$(TARGET_CFLAGS)" \
		LINUXKERNEL_INSTALL_DIR=$(BUILD_DIR)/linux-$(LINUX26_VERSION)
endif


TI_GST_PLUGIN_CONF_ENV+=$(TI_GST_PLUGIN_ENV)
TI_GST_PLUGIN_MAKE_ENV+=$(TI_GST_PLUGIN_ENV) CPPFLAGS='-DPlatform_$(TI_GST_PLUGIN_PLATFORM)' 

define TI_GST_PLUGIN_AUTOGEN
	(cd $(TI_GST_PLUGIN_DIR); \
		chmod +x ./autogen.sh; \
		chmod +x ./gst-autogen.sh; \
		$(HOST_CONFIGURE_OPTS) AUTOGEN_CONFIGURE_ARGS=--version ./autogen.sh; \
		$(HOST_CONFIGURE_OPTS) AUTOGEN_CONFIGURE_ARGS=--version ./gst-autogen.sh \
	)
endef

TI_GST_PLUGIN_POST_PATCH_HOOKS+=TI_GST_PLUGIN_AUTOGEN

$(eval $(call AUTOTARGETS,package/ti,ti-gst-plugin))
