################################################################################
#
# ti-dmai
#
################################################################################
TI_DMAI_VERSION:=2.05.00.14
TI_DMAI_FILE_VERSION:=2_05_00_14
TI_DMAI_SOURCE:=ti-dmai-$(TI_DMAI_VERSION).tar.gz
TI_DMAI_SOURCE_DIR:=davinci_multimedia_application_interface
TI_DMAI_SITE:=https://gforge.ti.com/svn/dmai/tags
TI_DMAI_SITE_TAG:=TAG_$(TI_DMAI_FILE_VERSION)

TI_DMAI_DEPENDENCIES=alsa-lib ti-framework-components ti-codec-engine ti-xdctools 

TI_DMAI_DIR:=$(BUILD_DIR)/ti-dmai-$(TI_DMAI_VERSION)

TI_DMAI_INSTALL_STAGING = YES

TI_DMAI_INSTALL_TARGET_DIR:=$(STAGING_DIR)/usr/lib/ti-dmai
TI_DMAI_INSTALL_STAGING_DIR:=$(STAGING_DIR)/ti/dmai-$(TI_DMAI_VERSION)

TI_DMAI_PLATFORM=UNDEFINED
ifeq ($(BR2_PACKAGE_TI_PLATFORM_omap3),y)
	TI_DMAI_PLATFORM=o3530_al
	TI_DMAI_DEPENDENCIES+=ti-codecs-omap3
	TI_DMAI_CODEC_INSTALL_DIR=$(TI_CODECS_OMAP3_INSTALL_STAGING_DIR)
endif
ifeq ($(BR2_PACKAGE_TI_PLATFORM_dm6446),y)
	TI_DMAI_PLATFORM=dm6446_al
endif
ifeq ($(BR2_PACKAGE_TI_PLATFORM_dm6467),y)
	TI_DMAI_PLATFORM=dm6467_al
endif
ifeq ($(BR2_PACKAGE_TI_PLATFORM_dm355),y)
	TI_DMAI_PLATFORM=dm355_al
endif
ifeq ($(BR2_PACKAGE_TI_PLATFORM_dm365),y)
	TI_DMAI_PLATFORM=dm365_al
	TI_DMAI_DEPENDENCIES+=ti-dvsdk-dm365
endif
ifeq ($(BR2_PACKAGE_TI_PLATFORM_omapl137),y)
	TI_DMAI_PLATFORM=omapl137_al
endif
ifeq ($(BR2_PACKAGE_TI_PLATFORM_omapl138),y)
	TI_DMAI_PLATFORM=omapl138_al
endif


TI_DMAI_MAKE_ENV = \
	PARALLEL_MAKE="" \
	USER_XDC_PATH=$(TI_CODEC_ENGINE_INSTALL_STAGING_DIR)/examples \
	XDC_INSTALL_DIR=$(TI_XDCTOOLS_INSTALL_DIR) \
	CE_INSTALL_DIR=$(TI_CODEC_ENGINE_INSTALL_STAGING_DIR) \
	CODEC_INSTALL_DIR=$(TI_DMAI_CODEC_INSTALL_DIR) \
	FC_INSTALL_DIR=$(TI_FRAMEWORK_COMPONENTS_INSTALL_DIR) \
	LINUXKERNEL_INSTALL_DIR=$(BUILD_DIR)/linux-$(LINUX26_VERSION) \
	CODEGEN_INSTALL_DIR=$(TI_CGT6X_INSTALL_DIR) \
	BIOS_INSTALL_DIR=$(TI_DSPBIOS_INSTALL_DIR) \
	LINUXLIBS_INSTALL_DIR=$(STAGING_DIR)/usr \
	CROSS_COMPILE=$(TARGET_CROSS) \
	VERBOSE="true" \
	XDAIS_INSTALL_DIR=$(TI_XDAIS_INSTALL_DIR) \
	LINK_INSTALL_DIR=$(TI_DSPLINK_INSTALL_STAGING_DIR) \
	CMEM_INSTALL_DIR=$(TI_LINUXUTILS_INSTALL_STAGING_DIR) \
	LPM_INSTALL_DIR=$(TI_LOCAL_POWER_MANAGER_INSTALL_STAGING_DIR) \
	MVTOOL_PREFIX=$(TARGET_CROSS) \
	PLATFORM=$(TI_DMAI_PLATFORM) \
	LD_FLAGS="$(TARGET_LDFLAGS)" \
	C_FLAGS="$(TARGET_CFLAGS) -fPIC"

$(DL_DIR)/$(TI_DMAI_SOURCE):
	(cd $(DL_DIR);\
		svn --non-interactive --username anonymous --password "" checkout $(TI_DMAI_SITE)/$(TI_DMAI_SITE_TAG) \
	)
	find $(DL_DIR)/$(TI_DMAI_SITE_TAG) -type d -name ".svn" | xargs rm -rf
	(cd $(DL_DIR)/$(TI_DMAI_SITE_TAG);\
		sleep 10; \
		tar -czf $(DL_DIR)/$(TI_DMAI_SOURCE) $(TI_DMAI_SOURCE_DIR)\
	)
	rm -rf $(DL_DIR)/$(TI_DMAI_SITE_TAG)

define TI_DMAI_CONFIGURE_CMDS
	$(MAKE) -C $(TI_DMAI_DIR) $(TI_DMAI_MAKE_ENV) clean
endef

define TI_DMAI_BUILD_CMDS
	$(MAKE) -C $(TI_DMAI_DIR)/dmai $(TI_DMAI_MAKE_ENV) all
endef

define TI_DMAI_INSTALL_STAGING_CMDS
	mkdir -p $(TI_DMAI_INSTALL_STAGING_DIR)
	cp -r $(TI_DMAI_DIR)/* $(TI_DMAI_INSTALL_STAGING_DIR)
	chmod -R +w $(TI_DMAI_INSTALL_STAGING_DIR)	
endef

define TI_DMAI_INSTALL_TARGET_CMDS
	$(INSTALL) -d $(TI_DMAI_INSTALL_TARGET_DIR)/apps 
	$(MAKE) -C $(TI_DMAI_DIR)/dmai $(TI_DMAI_MAKE_ENV) EXEC_DIR=$(TI_DMAI_INSTALL_TARGET_DIR) install 
endef

define TI_DMAI_UNINSTALL_STAGING_CMDS
	rm -rf $(TI_DMAI_INSTALL_DIR)
endef

ti-dmai-source: $(DL_DIR)/$(TI_DMAI_SOURCE)


$(eval $(call GENTARGETS,package/ti,ti-dmai))